swagger: '2.0'
info:
    version: v2
    title: User transaction
    description: Transaction API for argent Back OCR project 13
    termsOfService: None
    contact:
        name: Louis BERTHAUT
        url: www.louis/berthaut.com
        email: louis@berthaut.com
basePath: /
paths:
    /transactions:
        get:
            security:
                - Bearer: []
            tags:
                - User Transations
            summary: User Transactions API
            description: Show all month s transactions
            operationId: showMonthTansactions
            produces:
                - application/json
            parameters:
                - in: header
                  type: string
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
            responses:
                '200':
                    description: User transactions retrieved successully
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Transaction'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
    /transactions/{transactionId}:
        get:
            security:
                - Bearer: []
            tags:
                - User Transations
            summary: User Transactions API
            description: Show a transaction details
            operationId: showTansactionDetails
            produces:
                - application/json
            parameters:
                - name: transactionId
                  in: path
                  description: ID of transaction to return
                  required: true
                  type: integer
                  format: int64
                - in: header
                  type: string
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
            responses:
                '200':
                    description: User transaction retrieved successully
                    schema:
                        $ref: '#/definitions/Transaction'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - User Transations
            summary: User Transactions API
            description: Modifying transaction details
            operationId: modifyTansactionDetails
            produces:
                - application/json
            parameters:
                - name: transactionId
                  in: path
                  description: ID of transaction to return
                  required: true
                  type: integer
                  format: int64
                - in: header
                  type: string
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                - in: body
                  name: body
                  description: Update transaction attributes
                  required: true
                  schema:
                      $ref: '#/definitions/TransactionModify'
            responses:
                '200':
                    description: User transaction updated successully
                    schema:
                        type: object
                        items:
                            $ref: '#/definitions/TransactionModifyResponse'
                '400':
                    description: Invalid Fields
                '500':
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    Transaction:
        type: object
        properties:
            id:
                type: integer
                format: int64
            date:
                type: string
                description: transaction date
            details:
                type: string
                description: transaction description
            amount:
                type: number
                description: transaction amount
            balance:
                type: number
                description: account balance
            type:
                type: string
                description: transaction type
            category:
                type: string
                description: transaction category
            notes:
                type: string
                description: notes field for user
    TransactionId:
        type: object
        properties:
            id:
                type: integer
                format: int64
    TransactionModify:
        type: object
        properties:
            id:
                type: integer
                format: int64
            category:
                type: string
                description: transaction category
            notes:
                type: string
                description: notes field for user
    TransactionModifyResponse:
        type: object
        properties:
            code:
                type: integer
                format: int32
            type:
                type: string
            message:
                type: string
